services:
  web:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    env_file: .env
    environment:
      DATABASE_PATH: /data/db.sqlite3
    volumes:
      - database:/data

volumes:
  database:
